### ISSUE TITLE
http://download.opensuse.org/repositories/home:/p_conrad:/coins/xUbuntu_16.04/Release.gpg: Signature by key C39B1D488C8856171C1F6CB329D8C8DAC4447CF3 uses weak digest algorithm (SHA1)

### ISSUE THREAD

**Issue by NIXOYE** [namecoin/namecoin-core#137]
shouldnt namecoin be using something better?

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

NIXOYE:
> shouldnt namecoin be using something better?

Those packages are Namecoin 0.3.80, right?  Namecoin Core doesn't have
that issue, since there aren't any official GNU/Linux package repos,
and the binaries we've posted are signed with the same Gitian scripts
as Bitcoin Core.

I mean, yes, obviously it's bad that the 0.3.80 packages are using
SHA1, but I think scrapping 0.3.80 in favor of Namecoin Core is a
better solution than worrying about code that's obsolete.
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYV2XwAAoJELPy0WV4bWVwgwEP/iEHu517sE1xaj5GlgcCSfcx
j/cinxtEVyeBW6Ozk97s/n7Q2keJEW3lUoNU1nF2J8a0BGkWMox8MiN6q2EMdmbb
mmvHoSv7udyYR8ICRFOtVAaIAUbRVL/znbpSi5CeaefUSXGbJEMdSz+/JOUTksMm
+cjfMDnSfKjcnla9T7I+8ThG5HzKqWAvyYPS8wWvAkpBQa4Z2CURAfwF40XbNCF7
Ya++JFGcL0o/9l8lsDpxwQJX/HgfcZDsVJT5+qv0XJx0P3XOeNlru6R0bFgpakBg
PlQ3JVx32BoNo2BrfgrO+DEih7vasJaTKc7mxyz5SyMxR6th1VRubSfU8q/Ns/N3
QmkoL+QXbojUa1RDQ3Eh2MjUv6QG/kaqPDqA1wlOrySXyTicFtTkk+OK4uyW2u26
L1ZITHGYbhYCCPOgkHbfE/wmKXm7tlIgpEo/uEURFniY8hUSQUvRf8UNJ4t09HFe
fWJQSKPPb1FYTxBJkyqogfjqBwkJpb3OgpHcHU/6pko3fZCvhT6O7E42NutClw15
rheN/cEYkCnHPIwbBA5PtzkCgLwyL953lZtengUadcrKAPjUU5rjMSuzLka33Bak
SDtKSnirfMmSKietj1gVe1TD0eX9qndXtX4oLY/3OrJTFRJ0HQxZWf4ydYE6SB4E
D/OlSllkk+g9Fo/v+YCl
=RZpZ
-----END PGP SIGNATURE-----

**Comment by JeremyRand** [comment]
Closing since Namecoin Core has replaced Namecoin 0.3.80 for GNU/Linux users.
