### ISSUE TITLE
RPC: Better support for binary names and data

### ISSUE THREAD

**Issue by domob1812** [namecoin/namecoin-core#164]
The Namecoin protocol inherently supports binary data for both names and data, even if in practice ASCII names and JSON values are currently the de-facto standard for the majority of uses.  The RPC interface, on the other hand, is based on Unicode strings.  To better support pure binary data in an ideally backwards-compatible fashion, I suggest the following changes to the RPC interface (based on original input from @JeremyRand):

- All RPC methods that currently *return* names or values in any way (e. g., `name_show` or `decoderawtransaction`) will be changed to only return names/values in the current way if they are ASCII.  In addition, we add complementary JSON fields in the response that (always) return the name or value in hex.

- We introduce two new (off by default) configuration options `hexnames` and `hexvalues`.  If they are not set, then RPC methods that get names/values as *input* (like `name_update`) expect these to be pure ASCII and fail if not.  If they are set, then names and/or values are expected as hex string.

These two modifications will make it possible for applications built on top of the Namecoin RPC interface to properly handle binary data in both names and values, or just in values (e. g., more efficient encoding of data in the future).  They also make it less likely that such tools which implicitly expect ASCII strings are confused by non-ASCII Unicode returned by an RPC method.  Finally, I believe that the chosen approach is reasonably backwards-compatible, as it requires explicit "opt in" for the more disruptive changes.  It also does not complicate the existing RPC interface much more, like extra arguments to each name/value-accepting method would.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Daniel Kraft:
> The Namecoin protocol inherently supports binary data for both
> names and data, even if in practice ASCII names and JSON values are
> currently the de-facto standard for the majority of uses.  The RPC
> interface, on the other hand, is based on Unicode strings.  To
> better support pure binary data in an ideally backwards-compatible
> fashion, I suggest the following changes to the RPC interface
> (based on original input from @JeremyRand):
> 
> - All RPC methods that currently *return* names or values in any
> way (e. g., `name_show` or `decoderawtransaction`) will be changed
> to only return names/values in the current way if they are ASCII.
> In addition, we add complementary JSON fields in the response that
> (always) return the name or value in hex.
> 
> - We introduce two new (off by default) configuration options
> `hexnames` and `hexvalues`.  If they are not set, then RPC methods
> that get names/values as *input* (like `name_update`) expect these
> to be pure ASCII and fail if not.  If they are set, then names
> and/or values are expected as hex string.
> 
> These two modifications will make it possible for applications
> built on top of the Namecoin RPC interface to properly handle
> binary data in both names and values, or just in values (e. g.,
> more efficient encoding of data in the future).  They also make it
> less likely that such tools which implicitly expect ASCII strings
> are confused by non-ASCII Unicode returned by an RPC method.
> Finally, I believe that the chosen approach is reasonably
> backwards-compatible, as it requires explicit "opt in" for the more
> disruptive changes.  It also does not complicate the existing RPC
> interface much more, like extra arguments to each
> name/value-accepting method would.

Hmm... what happens if the user has multiple programs that want to use
the RPC port, and they have different expectations for the config
settings?  How does an RPC client check what the current value of
those settings is?

Admittedly I'm not incredibly familiar with how Bitcoin's JSON-RPC
works, but I think some Bitcoin RPC calls accept JSON objects as
arguments.  If that's correct, maybe the `name` and `value` args could
be checked for being a JSON object or a string.  String gets treated
as it currently is; JSON objects would have a syntax for specifying
both the encoding type and the actual data.  This might be a way to
avoid adding extra RPC calls while not forcing all RPC clients to
follow the same encoding rules.

Cheers.

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZH6k+AAoJELPy0WV4bWVwzkMP/3UmRyJ2gG6SUZhCwFwt4Lbg
6ou3+jr/B5XEQeOquqe1Fg0bodMd3ddWEuOBMNUWqvExQu8GCAuY+YVQymjNMCTE
+z34nQ9Gk7mtEW32OC23bgrlMsVY9rY4NQYIiKMB7tntaOFZYoyAHVfZ6S48ikkg
z6sa4SIuO1E7g1yTKFTUbHTQbSXNwry082knF8hN8a+yjSl3ffTE4kEJ/OU+XDX+
xm1v9Ov+FlYK3y1+BLWffJjkm85RdShKuD7D+pKBZbn6DJOvIt01M5hD5eZ5DEFO
+6DzeIYfBj2zfrgsTGNlwsHoA9W5Itlys/J1moKzWMABZAc4FWB6B1UiM2cZFdBh
ecGScekpFAfosi+78qph5rxqUJZyQr/n1oDkiKcgSOsszYsTUlBgBbIKeKP4jrKl
s1nIwpgy5Pi8G3iNVYUb4VpocEq96XKCfTB6fnvE/JCSKUh6PENOQlHY7lbFPJ/e
EVpoHlBnHRt/8FHaXwU987k3O6CB/1F2Cq/zKgKtSX/kt+PCjNJ8SIHAjxeM8jab
BiOqCtH6Ut4PKLfE0xQ+pKuHLDhb+MylvNtCFiGWZ3jHUfoyJGJDfKF4fhNMd+7j
/yxpi38+B8Jcf/7P2pwMu4sXBl+SDUQClYF95yd4vhp4U3lRq3imv3R5DflkSPwS
1aFVgtkWfxnWGttjP/Bh
=fyA0
-----END PGP SIGNATURE-----

**Comment by domob1812** [comment]
Good point!  However, I doubt that many people currently use multiple front-ends to the Namecoin daemon.  Thinking mid- to long-term, we could just make hex the default and have all automatic tools interfacing to the daemon use that.  People who manually play around with the command-line instead know what they are doing anyway and can choose their preferred setting.

Alternatively, we could auto-detect the encoding as you suggest.  But I wouldn't do that based on the value being JSON, since currently JSON (but as ASCII string) is used quite commonly for values already.  Instead, we could just auto-detect whether the string is valid hex.  For ASCII names with a namespace, this works, and I assume that also most values (especially plain-text JSON for domains) are not valid hex.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Daniel Kraft:
> Good point!  However, I doubt that many people currently use 
> multiple front-ends to the Namecoin daemon.  Thinking mid- to 
> long-term, we could just make hex the default and have all 
> automatic tools interfacing to the daemon use that.  People who 
> manually play around with the command-line instead know what they 
> are doing anyway and can choose their preferred setting.

I'd be really nervous about changing behavior of existing API calls in
ways that causes legacy software to do the wrong thing.  That said,
default of hex is probably relatively safe, since almost any
real-world legacy code will produce an error rather than the wrong
data being accepted.  So I might be okay with hex being the default.

> Alternatively, we could auto-detect the encoding as you suggest. 
> But I wouldn't do that based on the value being JSON, since 
> currently JSON (but as ASCII string) is used quite commonly for 
> values already.  Instead, we could just auto-detect whether the 
> string is valid hex.  For ASCII names with a namespace, this
> works, and I assume that also most values (especially plain-text
> JSON for domains) are not valid hex.

Does the bitcoin-cli implementation pass JSON object arguments as JSON
objects or as strings serialized from JSON objects (as defined by the
JSON-RPC spec)?  I always assumed it was the former, and therefore
clearly distinguishable from values of names (which are strings
serialized from JSON objects).  But I never actually checked with
Wireshark (or the source code).  If it's the latter, then this is
indeed a problem (although it seems like something that Bitcoin Core
should fix upstream, since I believe it violates the spirit of the
JSON-RPC protocol).

A rule of "Treat as hex if valid hex, otherwise treat as ASCII if
valid ASCII, otherwise error" seems like it might be okay, given that
most existing real-world usage is unlikely to be broken by this (and
any real-world usage that does get broken is nonstandard usage that I
honestly don't feel particularly bothered by temporarily breaking).

That said, I'd prefer if @hlandau and @ryancdotorg can comment on the
implications of either of the above proposals before I ACK them.  Hugo
and Ryan tend to be pretty good at catching things that I miss in
situations like this.

Other thing to consider is that, at some point in the future, we may
want to make it difficult to store ASCII data in name values, on the
grounds that CBOR is substantially more compact than JSON, and
therefore using CBOR reduces blockchain bloat.  If we want to make it
annoying to store ASCII data in name values, requiring that the
name/value args be passed as hex would make ASCII equally difficult to
store as binary data (whereas right now ASCII is slightly easier since
ASCII data doesn't need to be serialized from some other
representation).


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZNRIHAAoJELPy0WV4bWVwc4YQAIU2n5V3A1IdN8V+l2LuBlKf
Ltq17z1o+OcxltbM5kJZUu5nGPR3fQgwRmLIpmULry5x2c4oZ73ypOg9gKNe1zfZ
vXDkWi7UAp7q4S353LQ+1BCPQbnOGSwbMSSYU+Y6BmmJnKh0lTGHiDOemfp1nNuL
SfMb6uVgkuEc5J2SeAaJ/52JEThr6rCWwa3Y9wRWFEAc5j+Gn5IoUS3keMuEgdCS
ZwTEhtgDICvfTxfRXAWbopfV7Wit/VvMMJ6p15NAh/Mm9fzHLEGrGwcUMV2FKa7i
PuZ440KeOPcdHbYtH+ZzR+PGFuxanbpwX6d6e7wG3FLdnAlXqtW5fjKqSCQmYKbQ
PIwnG2K0uCLoQxIRDuW9I7M083wP2aVne10+AV5RSmwXYJecTn8ZnhI9cmfnpo16
nA1z5gueFpTegQMgkEIXoXsl6on8VTnpoCVuVUzLSFShd0KhRmuoEoSg2k9YOtM/
QMMaTjvqL/IePq4aYCeMzfIvHzqa4kBUnXbtU5SJ84R6nJQztBi5Mj8i5AReSo6Q
PegbC+pO2weLKDziC2qXLsdEaLVzncJ/NUyVVZ06KeSODOx9djfZDrn32iJDRtPm
AFenQUFoYVWVgFkBhRRn6oovGDxwFFEbZp1FN/ayQ0fjuOIw7Y8zkytKU4oDADiw
SbK/yZ6sXVwg/ffjhARY
=HQLR
-----END PGP SIGNATURE-----

**Comment by domob1812** [comment]
I think #194 is superior, so let's close this issue and implement proper binary name/data support there.
