### ISSUE TITLE
Problems w/ differences between internal RPC API and external calls

### ISSUE THREAD

**Issue by brandonrobertz** [namecoin/namecoin-core#184]
I've been merging the manage names tab code into the most recent upstream namecoin-core master branch and am running into issues between issuing name commands (`name_new` and `name_firstupdate`, specifically) using the internal C++ `JSONRPCRequest` API. When I issue `name_new` and `name_firstupdate` commands via namecoin-cli and the debug console in the UI, everything works as expected. When I use the UI flow, which uses `name_new` and `name_firstupdate` calls found in `wallet/rpcnames.cpp` I run an issue:

When I issue a name_new in the UI, it always succeeds. This is good and expected. When I wait 12 blocks and then issue a name_firstupdate, the call throws an error: "the name is already being registered". If I close namecoin-qt and restart it, I can see the name registered (via the `name_list` call). I have done some research here and have noticed that the mempool still sees the name pending registration there, despite its inclusion in a block.

Here's the code of the way I'm instantiating the call to `name_firstupdate`:

```
    jsonRequest.strMethod = std::string("name_firstupdate");
    jsonRequest.params = params;
    jsonRequest.fHelp = false;

    LogPrintf("executing name_firstupdate name=%s rand=%s tx=%s value=%s\n",
        name.c_str(), rand.c_str(), txid.c_str(), data.c_str());

    try {
        res = name_firstupdate (jsonRequest);
    jsonRequest.strMethod = std::string("name_firstupdate");
    jsonRequest.params = params;
    jsonRequest.fHelp = false;

    LogPrintf("executing name_firstupdate name=%s rand=%s tx=%s value=%s\n",
        name.c_str(), rand.c_str(), txid.c_str(), data.c_str());

    try {
        res = name_firstupdate (jsonRequest);
```

https://github.com/brandonrobertz/namecoin-core/blob/master/src/qt/walletmodel.cpp#L914-L922

It's possible that I am missing a piece, but I have followed the way it's being done in the unit tests as far as I can tell. I have only tested this in regtest mode, so it's also possible that there's a problem with only this use case, as well.

Any ideas? All relevant code is in my master branch https://github.com/brandonrobertz/namecoin-core

**Comment by domob1812** [comment]
The error you see ("this name is already being registered") should only occur if the name_firstupdate is already in the mempool.  Even more, if you get this error, then the call itself should not do anything else.  So since you say that the name registration is actually progressing even with the error, it means to me that you somehow already issue the name_firstupdate separately.  Maybe you've a bug in the preparing & issuing of the name_firstupdate?

I'm building your branch right now and will try if I can find any more details about the issue.

**Comment by domob1812** [comment]
Ok, I've successfully built the branch and registered a name on regtest with the Qt.  I get the exact behaviour you describe.  What is interesting, though, is the following:  First, I get log messages "Pending Name FirstUpdate Confirms: X" when mining blocks - but I get the message for each X twice.  Second, when I receive the error dialog you mention, I checked my wallet (while the dialog was still there) and it was already showing the name_firstupdate transaction.  So it really looks like there's a bug that causes the name_firstupdate to be sent twice (possibly because you send it at the same time when you print this "X confirmations" message).

**Comment by domob1812** [comment]
I think I found at least one bug:  In `sendPendingNameFirstUpdates` when the first update actually succeeds (https://github.com/brandonrobertz/namecoin-core/blob/master/src/qt/walletmodel.cpp#L1022), you do not remove the entry from the map `pendingNameFirstUpdate`.  Then the new transaction triggers another call to `sendPendingNameFirstUpdates`, which is why you get the error.

Removing the early continuation at the marked place makes it work for me, although then still the name table does not show the expiration for the new name until I restart - but I assume that is a separate issue.

BTW, I find the code to be quite messy in some places (which is probably also why this bug was introduced) and have suggestions for how to improve it in some places.  But I'll save that for the review or your PR. :)

Thanks for your hard work on this very important feature!

**Comment by brandonrobertz** [comment]
@domob1812 Thank you for looking through this. You are completely right. There are several bugs in the logic of the pending code.The pending isn't removed upon initial success of command. I'm not sure why this didn't surface in the original version (possibly bad merge on my part?) but I will certainly look forward to any suggestions you have for the coming pull request -- stylistic of otherwise.
