### ISSUE TITLE
Test for name script detection in P2SH outputs

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#241]
I suggest the following additional tests to make sure that P2SH and name scripts are interacting as expected:

1. Prior to the P2SH activation flag day, a name script prefixed to a P2SH scriptPubKey should be processed as a name script.
2. Prior to the P2SH activation flag day, a name script prefixed to a P2SH redeem script should *not* be processed as a name script.
3. Prior to the P2SH activation flag day, if a name script is prefixed to a P2SH scriptPubKey, and that scriptPubKey's redeem script contains a name script prefix, only the former should be processed as a name script.
4. Prior to the P2SH activation flag day, a name script prefixed to a P2SH scriptPubKey should be treated as "anyone can spend" (plus the usual rules for validating name scripts).
5. After the P2SH activation flag day, a name script prefixed to a P2SH scriptPubKey should be processed as a name script.
6. After the P2SH activation flag day, a name script prefixed to a P2SH redeem script should *not* be processed as a name script.
7. After the P2SH activation flag day, if a name script is prefixed to a P2SH scriptPubKey, and that scriptPubKey's redeem script contains a name script prefix, only the former should be processed as a name script.
8. After the P2SH activation flag day, a name script prefixed to a P2SH scriptPubKey should be subject to P2SH spending rules (plus the usual rules for validating name scripts).  (I *think* this one is covered by existing name_multisig tests, but I'm not 100% certain.)

**Comment by domob1812** [comment]
Just to confirm my understanding:  1-3 and 5-7 are exactly the same, except that the (same) behaviour should be tested both before and after activation, right?  Also, 3) includes both 1) and 2) - although it might make sense to still have 1) and 2) separately just in case.

I think that the existing `name_multisig.py` test covers none of the items from the list if one is precise.  It covers 3) and 8) somewhat (as you say), except that it tests this *before* the activation and through the *mempool (policy) rules* that always forbid such transactions already now.

Due to the policy rules, it would be hard to actually verify 4).  But I can extend the test to run both before and after activation, and to have explicit tests for 1) to 3) - in particular, to cover *redeem scripts with name prefixes*.  (That will be somewhat non-trivial, though, as it means messing around with raw scripts and signatures; I *think* that the regtest framework of Bitcoin should have all we need for it, but if not, I'm afraid we might have to simplify the test.)

**In any case, I'm pretty certain that the existing code implements all of these things correctly.**

**Comment by JeremyRand** [comment]
> Just to confirm my understanding: 1-3 and 5-7 are exactly the same, except that the (same) behaviour should be tested both before and after activation, right?

Yes, that's correct.

FWIW, the primary reasoning for having these tests is that it makes certain that we haven't accidentally turned the P2SH softfork into a hardfork.  (Since changing the definition of what constitutes a name script would be a hardfork.)

**Comment by domob1812** [comment]
Yes sure, it makes sense to have them - and they reflect also my own understanding of how P2SH should work with name scripts.  I'm pretty sure the logic works like that (it would actually require some extra effort to make name scripts inside the redeem script take effect, so this is "by default"), but having at least those tests that are possible reasonably easily makes sense.  I'll look into that when I have time.

**Comment by JeremyRand** [comment]
Once we've dealt with these tests for P2SH, I'm probably going to file a similar issue for SegWit.  Given that SegWit changes how scripts are interpreted (e.g. via script versioning), the tests in this issue are likely to be analogous to tests that we'll want for SegWit.  But I'll save that for after we've covered P2SH.

**Comment by domob1812** [comment]
Sure.  But since both P2SH and Segwit just change how signatures are verified, I honestly don't think there's much risk to accidentally break Segwit if we do not also break P2SH.  (Note that the script verification logic is not at all tied to any name logic - that lives inside the block validation code at an entirely different level.)

So I think it would be good to have basic tests with names sent and updated to/from segwit addresses, I don't think we need to (or should) duplicate all the points above for segwit - this just creates a mess of complex and hard to debug/read/understand tests.  (But yes, let's cover P2SH first and then think about segwit.)

**Comment by domob1812** [comment]
Closing this now that #243 is merged and there were no comments on the PR about missing tests.  @JeremyRand, feel free to reopen if you think that this is not addressed adequately yet.
