### ISSUE TITLE
Warning message "do not use for mining" inconsistent with current recommendations

### ISSUE THREAD

**Issue by cassiniNMC** [namecoin/namecoin-core#29]
The message "do not use for mining or merchant applications" in main.cpp and qt/bitcoinstrings.cpp is outdated. It contradicts the instructions in the [OpenSSL Consensus thread](https://forum.namecoin.info/viewtopic.php?f=2&t=2354):

> ... all mining pools MUST upgrade to Namecoin Core ...

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

On 09/04/2015 03:16 PM, cassiniNMC wrote:
> The message "do not use for mining or merchant applications" in
> main.cpp and qt/bitcoinstrings.cpp is outdated. It contradicts the
> instructions in the OpenSSL Consensus thread 
> <https://forum.namecoin.info/viewtopic.php?f=2&t=2354>:
> 
> ... all mining pools MUST upgrade to Namecoin Core ...
> 

I'm pretty sure that's because it's built from a Git commit rather
than a version tag.  Once we have version tags for official releases,
I believe that message will no longer be visible.

- -Jeremy

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJV6bavAAoJEAHN/EbZ1y06qUQQAKvQjgijftxhzB1vMx/qalq7
7oR0tClQvU/UhpC5IN+O96QoFVbBd5Vg14155ANe5B0Q0JFgFLLra0dNjSBYuhsk
gzkzeH6QHsyNM27w0Q8XaRrXYgjFUrdsQqkPtIHp+LQ4OeRbFvFIAFGZxo0lA0Fg
kV+XhdXq9NPGA2ztiTBpv+sLg1pJIUC+43lM5U6kik+8kqC2a6m1NQpDO5lFRd0T
mRuFqxHfBuyy5rnHPV6fzhNBTrU9/s5EfluqCPvl7u2CRX0TSi15Rs2VWJRXG1n/
gW2n6ts7Ad0VPXl/Zt7QZEG33mrDC0CpeNz75YuAPn+jMm/AhzK8B1zzZZZ/IhuU
3pvLMFUS22F7rWIkDLWMNakC4XMX4gWxQk7pCHYGj6U7V8TgJ3nOaosWKK8JFco2
Qjy/6F0AsyPzWxLcmUNyL4JeDfCQjicAtNdXl1y/SW09USwW+Tuz3XpNfEdmXHRe
kIoDJub4VnWyOVg/75l2pYnMwPkWw9OGqsbG0ddFUcEna0NN8Vz2V/ACM2HC4xwJ
nAjWyzZV1SQMomRRQ2Uq8iGgRSP71WcmRZAxtQu2NHxY8CShw7zCT7uRjY4ikNWR
MNkRaktMxB0B15BQjuttVQEKqrl4DR91/YVNzlIe+0F2qKDUlA8wji0kkZUbAM42
xTRoxVO1fDqTJjLMns2W
=bGFg
-----END PGP SIGNATURE-----

**Comment by domob1812** [comment]
Yes, that's pretty much what's happening.  I've never dealed with versioning so far, but I believe that there's a flag next to the version number that indicates whether the build is supposed to be stable or experimental.

We should probably branch off a release, at least when we think we are ready to do one.  Apart from that, we could provide builds where just the flag is changed for the current semi-"emergency" situation if the warning confuses miners.

**Comment by phelixbtc** [comment]
tbh with the Windows release in the hurry I could not find the flag to do it. The one I thought would do it in clientversion.h 'CLIENT_VERSION_IS_RELEASE' does not do the job, at least not on its own. If somebody figures out how to remove the warning let me know.

**Comment by fsb4000** [comment]
@phelixbtc 
Hi. I figured out how to remove the warning.
![warning](http://i.imgur.com/zcTNrZ8.png)

1. Do configure as usual.
2. Open src\config\bitcoin-config.h
3. Search #define CLIENT_VERSION_IS_RELEASE
4. Change value to true
![far](http://i.imgur.com/jYxzHvF.png)
5. Save file.
6.Do make as usual.

**Comment by domob1812** [comment]
This is partially true.  There are two places where the flag appears.  One is in `src/clientversion.h`, but I'm not sure under which circumstances this is used.  The one that makes the change for me is the one mentioned, although the file is autogenerated.  The change should be made in `configure.ac` instead.

Note that the 0.12 branch is already set to "release".

**Comment by domob1812** [comment]
Closing this.  The release branches (`0.16` currently) already set this "is release" flag to true, so the warning should not apply on them.  We need a proper and more structured release process, but this issue is not (really) about that.
