### ISSUE TITLE
Should the Payment Protocol be rebranded?

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#291]
I notice that the Payment Protocol protobuf definition in Namecoin Core still references `org.bitcoin`: https://github.com/namecoin/namecoin-core/blob/ffdbe14955e79d88d5c02ee3857f41e055385e50/src/qt/paymentrequest.proto#L12

I'm not familiar enough with the Payment Protocol to know whether that's a bug, and what the implications are if we change it to `org.namecoin`.  @domob1812 Any thoughts on this?

**Comment by domob1812** [comment]
I'm not familiar with the payment protocol either, but that option in the proto file basically specifies the Java package in which the generated protocol buffer class (for Java only) will be placed.  I imagine that this mostly affects BitcoinJ or other Java implementations that use the payment protocol, and likely not even that, since they probably have their own .proto file for it.

So all in all, I believe we can safely change this, but it won't really have any impact at all.

**Comment by JeremyRand** [comment]
Okay.  I'll see if I can find time to inspect how BitcoinJ uses those classes, and whether anything will break if we change it.  AFAICT, if Namecoin made any changes to the Payment Protocol (e.g. something name-specific) then we'd want to use a different Java package from Bitcoin Core to avoid collisions.  It's not clear to me whether there's any use case for Namecoin-specific additions to the Payment Protocol.  Anyway, this is low priority, so I'm unlikely to deal with it anytime soon, I just wanted to make sure the issue exists in GitHub (it came to my attention because my rebranding static analyzer for Electrum-NMC flagged it, and I didn't want to whitelist it in the static analyzer without making an issue for it).

**Comment by yanmaani** [comment]
BIP70 has been removed from upstream, close this?

**Comment by domob1812** [comment]
Makes sense.
