### ISSUE TITLE
the value is too long (code -8)

### ISSUE THREAD

**Issue by loskiq** [namecoin/namecoin-core#327]
I am trying to update my domain (name_update), but Namecoin Core (0.18.0) throws an error:
```
the value is too long (code -8)
```
I understand that this value is too long, but I need exactly this value. I can’t cut it.

**Comment by mkg20001** [comment]
Depends, maybe you can. In JSON you can remove the whitespace and newlines between keys/values.

**Comment by domob1812** [comment]
There's a limit of 520 bytes per value.  If you need a longer one, first try removing whitespace and stuff like that as @mkg20001 suggested.  If that isn't enough, you can think about splitting it up e.g. using `import`.  @JeremyRand can probably give you more detailed information if it is about .bit domains.

**Comment by JeremyRand** [comment]
@loskiq Can you provide more details about your intended use case?  Blockchain space is expensive, so Namecoin deliberately limits the value size in order to reduce externalized costs.  Depending on your use case, we might suggest ways to decrease the size of your data, or we might recommend not using Namecoin for this.

**Comment by yanmaani** [comment]
Vote to close.
