### ISSUE TITLE
namecoind 0.18.0 sync issue (Iran)

### ISSUE THREAD

**Issue by m4hdi1995** [namecoin/namecoin-core#336]
Hello, i'm running namecoin daemon on a server and it doesn't sync with the network, server location is iran, we have had this problem with verge and it has been fixed with '''--without-tor''' flag (tor is blocked in iran), what can we do for NMC?
thanks.

**Comment by domob1812** [comment]
Thanks for your report!

Unlike Verge (which I believe heavily markets itself as "anonymous", while that only means that it uses Tor by default), Namecoin can use Tor but does not do so by default (or mandatorily).  So my first guess is that Tor isn't actually your problem, unless you specifically tell Namecoin to use tor.  But to make sure, you could try to pass `-onlynet=ipv4` (or set `onlynet=ipv4` in your `namecoin.conf` file), which explicitly instructs Namecoin to only make plain IPv4 outgoing connections.

Perhaps your issue is initial seed discovery.  I don't know why that would happen (especially why Iran would be more likely for it to happen), but there could be some issue with the DNS seed.  Have you tried setting `-addnode=a.b.c.d` for some known public nodes (you can find those with an internet search)?  Also, does your `debug.log` file show some things that may help in figuring out what the actual issue is?

**Comment by m4hdi1995** [comment]
@domob1812 thank you for your respond, yes it's not the tor because it's as you said it's disabled, could you post some mainnet nodes here or a link to find some? because i didn't find any using google

**Comment by m4hdi1995** [comment]
i have grabbed some from https://github.com/namecoin/namecoin-core/blob/master/contrib/seeds/nodes_main.txt but most of them doesn't work and it syncs very slow
