### ISSUE TITLE
Error in command name_history

### ISSUE THREAD

**Issue by Tradefreak** [namecoin/namecoin-core#342]
Making a request with the command `name_history` for the name `d/globalresearch` <s>leads to an error in the penultimate output, showing `"expires_in":-38710`, so 38710 blocks ago instead of 74710 blocks ago at the current block height of 495709 (update was at block 420999). This</s> leads to errors in the development of a blockchain explorer. <s>Might be of course that this in a defect record on the blockchain - then this would be a historic issue!</s> By the way: Will this Namecoin qt client ever been updated?

**Comment by domob1812** [comment]
By definition, `name_history` shows you all the historical records of a name, including outdated ones (`name_show` only shows the current entry, matching the *last* record from `name_history`).  So the `expires_in` field of a previous record is negative in many cases, matching that the name would be expired if that record would be the last one (i.e. it hadn't been updated with subsequent records).

If a block explorer somehow shows data corresponding to old records of `name_history`, then that is a bug in the block explorer and not Namecoin Core.

The only thing I could see here as possible suggestion for Namecoin Core is removing `expires_in` and `expired` fields for the non-current `name_history` records, as they are probably mostly confusing (and the data can be computed anyway from `height` in case it is needed).  Is that what you think we should do?

> By the way: Will this Namecoin qt client ever been updated??
Namecoin Core (including the Qt frontend) is up to date with Bitcoin Core.  If you are talking about the "name UI branch", then I unfortunately don't know, because this was an effort by another developer who seemed to have lost interest a long time ago.

**Comment by Tradefreak** [comment]
It's not necessary to change anything. I just reported a bug for this specific name, showing `"expires_in":-38710` instead of `"expires_in":-74710` (at that moment). This result comes directly out of the Qt node, and as I mentioned in the [issue 343](https://github.com/namecoin/namecoin-core/issues/343) (what you closed unfortunately without solving it) the version 13.99 is the only one GUI version available since long time. Please don't refer to the Electrum NMC, as this node is useless!

**Comment by domob1812** [comment]
Ok, but then please explain why you think the correct value is -74710.  I think that -38710 (or thereabouts) is actually correct for the last-but-one historical record.  That is what corresponds to 36'000 blocks after that record's `height`, in relation to the current block height.  Or am I missing something?

There is a UI, namely Namecoin Core including the Qt wallet.  It just does not allow you to do name operations in the current version.

**Comment by Tradefreak** [comment]
Yeah, you're right! Seems so, that this was just a bug of the example blockchain explorer I linked at first and deleted afterwards, [after I revealed it as scam](https://t.me/namecoin_online). Looking at the JSON output of the node I was indeed confused about the registration and expiration date, so my fault! Anyway no need to chance something in the Namecoin clients. About the Namecoin Core v. 0.19 I have another issue anyway which I'll describe in another issue here. Thanks so far!
