### ISSUE TITLE
Namecoin Core 0.22.0 (GNU/Linux x86 64-bit) download?

### ISSUE THREAD

**Issue by dvdsim711** [namecoin/namecoin-core#490]
Hello,
not a feature request, just dont know where else to post this question.

I run a Full node and want to update using the "Namecoin Core 0.22.0 (GNU/Linux x86 64-bit)" package as I've been doing for the last 2 years for previous releases. 
The namecoin.org downloads page has not been updated to include the latest 0.22.0 release. 
Does anyone know how to get the "Namecoin Core 0.22.0 (GNU/Linux x86 64-bit)" download?

**Comment by yanmaani** [comment]
It's not released yet, it should be soon, just wait for a bit. You can always build it yourself if you want to try it earlier.

I think [namecoin/namecoin.org](https://github.com/namecoin/namecoin.org] is where you should file the issue, but it's not really a website problem because it's not released yet.
