### ISSUE TITLE
The cybersquatter called Uwe Martens 

### ISSUE THREAD

**Issue by ghost** [namecoin/namecoin-core#514]
Doing some research I have found out that the Bitmessage address **BM-2cXeN1HuY8h7nYAkPj1mny4Ki4wywPorwM** and the domain **domaindeals.pro** belongs to the same person called **Uwe Martens** who currently on the Telegram channel Namecoin NMC https://t.me/namecoin selling names from the d/ namespace for tens of thousands of dollars. 

**Uwe Martens** appears to be harassing the Namecoin community both on WikiPedia and other places online, examples include but not limited to: 

- https://en.wikipedia.org/wiki/Talk:Namecoin#Undeclared_donation_to_Namecoin_contributors
- https://en.wikipedia.org/wiki/Talk:Namecoin#The_added_namecoin.pro_links_are_spam_and_not_relevant

I have also found a complaint to **NLnet Foundation** written by **Uwe Martens**: https://t.me/namecoin_online/97

To make it worse **Uwe Martens** on the namecoin.pro website distributing both Electrum NMC and Namecoin Core with modifications in particular IP addresses, logos... While distributing modified versions is not necessarily illegal scamming people in private messages on the fake Telegram channel misleading unaware users for being an official Namecoin channel is certainly can prompt legal action. 99.9% of the "users" on that fake Telegram https://t.me/namecoin channel are fake. 

**Uwe Martens** has between 15-20,000 names squatted in the d/ namespace which is a significant issue and only can be resolved if the d/ namespace is completely abandoned. 

I request @JeremyRand, @domob1812, @yanmaani, @ss11s @phelixbtc @khalahan and everyone else to take this issue very seriously since it is a very clear fraudulent and hostile attack on the Namecoin project. 

@JeremyRand should write a post about this issue to the Namecoin.org website as well.

**Comment by blocktraveler** [comment]
I wonder when Zoltan Konder finally realizes that his time in the Namecoin project is over? Recently he entered the Namecoin Telegram group with one of his one-way accounts [begging for 10 NMC](https://t.me/NameCoin/55855). After not getting them, he told that he was about [to buy all possible namespaces on the Namecoin blockchain](https://t.me/NameCoin/55973) from an unknown user for 10,000 USD. Or he would somehow register them himself and start some kind of Handshake version of Namecoin. Completely confused as usual. Last year he wanted to become admin of this Telegram group, but after his request was rejected, he started making his trouble in the Freenode IRC channel, all Namecoin related Discord servers and now here, over and over with the same “arguments”.

For those who don't know this toxic user, the search phrase: _Zoltan Konder human rights_. He has scammed people out of hundreds of thousands of USD with his fake human rights foundation, payments received via Bitcoin on a known address. His scam domain was even blocked in WayBack Archive. He's known for his death threats all over the internet and even threatened the US Trademark Office for not granting him the trademark. He gave the impression of believing that the real Human Rights Foundation with Kaspersky wanted to murder him, so his death threats against them would be justified and so on
[If you look at the blockchain](https://nmc.tokenview.com/en/tx/56b7227649aa6ecd10aeaf6e6e448a72211a37956ddb633b2d9532e5a3fc048b), you have good reason to believe he's the well-known waste recycler `onehundrednmcpername@protonmail.com`. This user is known in the Namecoin community for his psychotic responses and aggressive behavior. `BM-2cXeN1HuY8h7nYAkPj1mny4Ki4wywPorwM` recently started to change his domain grabbing strategy and wanted to rule out the well-known drop-catch service domaindeals.pro (but had no chance btw). The real reason why Zoltan Konder joined the Namecoin group was [to ask how to do it](https://t.me/NameCoin/55879). After not getting an answer and eventually getting banned again, he was just frustrated that he only gets the expiring garbage, so he came here.

By the way, it should be referred to the [Domain Trading Policy](https://namecoin.pro/SitePages/Namecoin%20in%20competition.aspx#Policy), which both the BM-user and domaindeals.pro adhere to without question. Regarding the “modified” files: no Github fork has been created yet, so all binaries offered for download are the original files, which can be easily verified by their hash. The main reason for creating the new website was to replace the previously deleted Namecoin wiki, which was deleted by Jeremy Rand without prior consultation with any of the contributors. Last but not least, it is needless to mention that Namecoin is a pure open-source project that is not backed by any company. Anyone can contribute anywhere and there’s not a single instance that could insist on being the only one. Inactive members are regularly kicked out of the Telegram group btw, so these 2000 members were offline a month for the longest. Just for the records: This group [has been established in December 2016](https://t.me/NameCoin/8) and is thus the oldest and most active Namecoin community.

**Comment by namecoindeveloper** [comment]
I suppose this @blocktraveler is Uwe Martens. Cybersquatter. 

Which Human Rights Foundation that guy impersonating? There is over 177 different "Human Rights Foundation" in the world. https://opencorporates.com/companies?jurisdiction_code=&q=human+rights+foundation&utf8=%E2%9C%93 How this related to Namecoin?

Seems like the op is correct and you smearing people who expose that you are a fraud squatter Uwe Martens. Even according to yourself https://t.me/namecoin is created in 2016.

> The main reason for creating the new website was to replace the previously deleted Namecoin wiki, which was deleted by Jeremy Rand without prior consultation with any of the contributors. 

Is this a joke? Your shit "website" you made in Microsoft Word has nothing to do with the old wiki. 

You never contributed anything to the Namecoin project nor you running a legitimate Telegram group, I did took a look and all it's members are fake. How much you paid for those followers?

**Comment by namecoindeveloper** [comment]
Uwe Martens did you smeared **CoinMarketCap**.com for deleting your scam? https://bitcointalk.org/index.php?topic=5228762

You deserve to be punched in the mouth for going around and pretending that you representing the Namecoin project.

**Comment by namecoindeveloper** [comment]
I suppose this @blocktraveler is Uwe Martens the cybersquatter. 

Which Human Rights Foundation that guy impersonating? There is over 177 different "Human Rights Foundation" in the world. https://opencorporates.com/companies?jurisdiction_code=&q=human+rights+foundation&utf8=%E2%9C%93 How this related to Namecoin?

Seems like the op is correct and you smearing people who expose that you are a fraud squatter Uwe Martens. Even according to yourself https://t.me/namecoin is created in 2016.

> The main reason for creating the new website was to replace the previously deleted Namecoin wiki, which was deleted by Jeremy Rand without prior consultation with any of the contributors. 

Is this a joke? Your shit "website" you made in Microsoft Word has nothing to do with the old wiki. 

You never contributed anything to the Namecoin project nor you running a legitimate Telegram group, I did took a look and all its members are fake. How much you paid for those followers? 

Uwe Martens did smeared CoinMarketCap.com staff too for deleting his attempted Namecoin scam: https://bitcointalk.org/index.php?topic=5228762

**Comment by namecoindeveloper** [comment]
Uwe Martens claimed that @JeremyRand deleted the Namecoin Wiki and that is **completely false**. The wiki is here: https://github.com/namecoin/wiki

I don't see a single contribution from Uwe Martens to Namecoin at all, all he does is scamming people, harassing everyone who in any way involved in the Namecoin project and squatting tens of thousands of domains at the same time. 

Both @yanmaani and Jeremy Rand has been slandered by Uwe Martens on https:/t.me/namecoin, https://t.me/namecoin_online and on WikiPedia.

Jeremy Rand had made it very clear that **Uwe Martens is not a contributor to or otherwise involved with Namecoin**. Uwe Martens is a well known squatter criminal who pretending to be the official Namecoin representative. 


Quote from Uwe Martens (https://en.wikipedia.org/wiki/Talk:Namecoin#The_added_namecoin.pro_links_are_spam_and_not_relevant):

> outdated website at namecoin.org, which doesn't provide any usefull information. One only has to enter the well-known Telegram communities and be regularly confronted with the absolutely basic questions of how to register .bit domains and so on after Jeremy Rand, the sole content creator of namecoin.org, single-handedly decided to shut down the original Namecoin wiki without consulting a single other contributor before! What is mentioned in the WP article has not been "the official website" for a long time, but only the personal website of Jeremy Rand, whose only "community" consists of the IRC channel on Libera Chat with just around 14 members. In contrast, namecoin.pro is supported by a large community on Telegram with more than 1000 members in several groups, as linked in the imprint. In contrast, namecoin.pro provides binaries from the official GitHub repository with the adequate description and instructions. The technological content of namecoin.pro exceeds the content of the poor WP article by far and can clearly be used as a reference for the issues in question, which has been mentioned in a large "issue box" for over 6 years now. Defaming another Namecoin coder as "not a contributor to or otherwise involved with Namecoin" also clearly seems to be a conflict of interest just of the OP of this talk page section, as namecoin.pro, without doubt in contrast to namecoin.org, provides working browser add-ons to resolve blockchain domains, means to make Namecoin finally practically usable after more than 10 years of deep sleep. It has to be mentioned here again that Namecoin is not backed by any company or organization, there is not even a whitepaper and namecoin.org has never published any such paper, so there doesn't exist any "official" entity as Namecoin is a pure community project with equal contributors. namecoin.org only provides ridiculous fantasy positions like "Chief Namecoin Scientist", "Lead Application Engineer" and other jokes. I mean, namecoin.pro could offer the same fantasy positions, but of course it doesn't. The relevant threads on Bitcointalk might be of interest here, where you can read that Namecoin is more or less considered dead

I propose that the Namecoin project collectively take legal action against Uwe Martens in Germany.

**Comment by blocktraveler** [comment]
🥱 For those who are interested (just the first Google results):

• Crime Digest U.S.A.: [Project Veritas received a death threat](https://midtowntribune.com/2020/10/29/project-veritas-received-a-death-threat/)

• Thor Halvorssen: [In the past day Hungary’s Zoltan Konder has sent more criminal threats to me](https://twitter.com/thorhalvorssen/status/1343637643540611073)

• Bitcointalk: [Scam accusation against user humanrightsfoundation](https://bitcointalk.org/index.php?topic=5179215.0)

• IRC log #bitcoin-core-dev 2021-02-03: [Zoltan Konder has been issuing serious death threats against the Tor project](https://gnusha.org/bitcoin-core-dev/2021-02-03.log)

**Comment by namecoindeveloper** [comment]
I don't see anything wrong with Zoltan, but I see that you **Uwe Martens** are talking nonsense, totally unrelated to the Namecoin scams you running. Attacking Namecoin contributors, promoting your fake Namecoin Telegram channel and that shit namecoin.pro "website" that you using to spam the namecoin block chain, wikipedia, and many other places. 

You even tried to attack and place your link into the CoinMarketCap listing page of Namecoin and when they admins deleted your spam you slandered them in the name of the Namecoin project. You sending letters to NLnet Fundation slandering there too both @JeremyRand @yanmaani and others who working hard on Namecoin.

**Comment by blocktraveler** [comment]
[12-28-2018
name_firstupdate
d/universaldeclarationofhumanrights
{onehundrednmcpername@protonmail.com}](https://nmc.tokenview.com/en/tx/ff317e83eee04e777a1c36aecb36156cfdef12ae8d34804917615869c7a75524)

⚠️ **Warning:** Everyone is advised not to deal with that hobby squatter `onehundrednmcpername@protonmail.com`! Domains he previously bought himself from `BM-2cXeN1HuY8h7nYAkPj1mny4Ki4wywPorwM` had been financed by his scam foundation! It has to be noted that those domains like `d/crypto` had recently been sold by this user again at ridiculous sales prices as he was needy.

**Comment by namecoindeveloper** [comment]
Can you stop spamming? Would be appreciated. Some of us are interested in exposing **Uwe Martens** and his scams and attacks on the Namecoin community. If you don't talk about **Uwe Mertens** (I bet that you're Uwe Martens) then just go and find yourself a new hobby.

**Comment by blocktraveler** [comment]
🤣

**Comment by namecoindeveloper** [comment]
So this Zoltan guy working for these scammers in this YouTube video? I don't think so.

Garry Kasparov Unhinged! - His **Human Rights Scam Exposed** w/Thor Halvorssen
**https://www.youtube.com/watch?v=fhhyNm5rhHc**

The same scammers, kicked out from the United Nations for terrorism: https://wikileaks.org/plusd/cables/08USUNNEWYORK516_a.html

![bush](https://user-images.githubusercontent.com/106346841/170869278-161f099f-1d1e-48f7-aae5-00d2b17801c9.gif)

**Comment by namecoindeveloper** [comment]
Keep on topic, we talk about Namecoin and **Uwe Martens** who is squatting, defaming, slandering and attacking everyone in the Namecoin project.

**Comment by domaindeals** [comment]
Here are some screenshots from **Uwe Martens** he clearly shitting on @JeremyRand and @yanmaani while acknowledge it that he himself is a loser who "started coding in 2018". 

## @yanmaani is a shit dev according to Uwe Martens who himself a "pro"
![*-16](https://user-images.githubusercontent.com/106484358/170880620-567db589-27a3-4fd4-bcbe-e5d77c889ce8.png)

![*-13](https://user-images.githubusercontent.com/106484358/170880657-c338d51a-452a-4baf-b142-d782daba99fb.png)

## Uwe Martens accusing @JeremyRand and @domob1812 with defrauding NLnet Foundation
![*-17](https://user-images.githubusercontent.com/106484358/170880691-562a6855-2bd2-4706-b196-4145752fe726.png)

![*-18](https://user-images.githubusercontent.com/106484358/170880842-a4b7fc2a-855a-4947-9849-cfb415436113.png)

## Uwe Martens scamming Namecoin users since 2018
![*-10](https://user-images.githubusercontent.com/106484358/170880904-43a7e632-de73-45de-b3c9-6ecbe5d9c24c.png)

# I propose completely abandoning the d/ namespace so Uwe Martens and his fellow squatter scammers will lose everything.

**Comment by blocktraveler** [comment]
The Namecoin community, means  our 2000 members on Telegram and a few hundred on Discord, would like to thank Zoltan Konder for the entertainment! Instead of spamming screenshots, it would have been enough to post the links (uh, forgot, he's banned). For the interested readers: Which namespaces are used is  in the end a matter of the front-end application accessing the blockchain. The new browser add-ons shown in action in namecoin.pro will not only resolve `.bit` domains, but also others such as `.nft`, `.nft` and `.crypto` pTLDs, which will of course be assigned to their own namespace. Namecoin as a blockchain is a cryptographically highly secured key/value store. How it is used is just a matter of specifications, which are always a "should be", not a "must be". But of course, the `.bit`  pTLD will always be associated with the `d/` namespace. I recommend closing or deleting this issue to avoid further time wasting.

**Comment by domaindeals** [comment]
Nobody use your shitty browser addon because you're a fraud bitch. 

Regarding `.bit` we can easily move the tld to other namespace. :)

**Comment by domaindeals** [comment]
> The Namecoin community, means our 2000 members on Telegram

You're clearly a scammer.

> and a few hundred on Discord

Oh yeah? Historical Domains aka https://historicaldomains.io and https://twitter.com/HistoricDomains was forced to shutdown because you harassed them too.  

We not delete anything, we let it here to see everyone who is **Uwe Martens**. For years you harassing @JeremyRand @yanmaani and @domob1812 too. I have taken action against the fake Namecoin Telegram channel https://t.me/namecoin and it will be transferred to Jeremy Rand who is our community organizer.

**Comment by yanmaani** [comment]
I am not associated with either of these people, both of whom are clowns. (I note that neither party has contributed anything to this project but moderation work.)

* It is not possible to implement a functioning transaction queue in two lines of code.
* Zoltán Kondér is not `onehundrednmcpername@protonmail.com`.
* It would be a terrible decision to get rid of the `d/` namespace, and squatting is not a serious problem anyway.

Please also note that this is the repository for the Namecoin Core daemon. Whatever it is that you wish to discuss, it does not appear to have the character of a technical issue. (In particular, suggestions to deprecate or create new name spaces are best suited for the namecoin/proposals repository.)

You may also want to consider establishing a fork of the Namecoin project where you may freely implement such ideas as you would like without being held down by the rigors of code review and technical standards. On that note, the Namecoin project wholeheartedly endorses your decision to begin domain activities in other and less crowded namespaces.

**Comment by blocktraveler** [comment]
> You may also want to consider establishing a fork of the Namecoin project where you may freely implement such ideas as you would like without being held down by the rigors of code review and technical standards.

Thx, but as one of those you referred to as "clowns" I wanted to note firstly that I am not arguing with this known troll, just commenting on this for the bystanders who brought this conversation to my attention here. Secondly, as I said, namespace usage is not something that needs to be coded into the software wallets (despite perhaps recognizing different namespaces as domain namespaces while registering). It's completely up to the front-end app how to use Namecoin's key/value store, it wouldn't even need a consultation with code contributors or the community as we've seen (unfortunately) with OneName aka Blockstacks back in 2014. In our case, it was sufficiently discussed in advance with the Namecoin community, which mainly consists of the active communities on Telegram and Discord, which have _slightly_ more members than your IRC channels with 14 members . No further comments to add to that.

**Comment by domaindeals** [comment]
@yanmaani clown is your mom who shit you to the world and hit your head at birth.

**Comment by domaindeals** [comment]
> On that note, the Namecoin project wholeheartedly endorses your decision to begin domain activities in other and less crowded namespaces.

You the clown have no authority to decide what is endorsed and what not. 

Namespaces such as id/ are hardcoded to Electrum-NMC by the clowns who themselves squatting the d/ namespace. One of those clowns in @domob1812 aka Daniel Kraft who offering domains for tens of thousands of dollars. 

The other clown is @yanmaani who is onehundrednmcpername@protonmail.com. 

The clowns who hardcoded other namespaces into Electrum-NMC don't want to abandon the d/ namespace because they would lose money too. Non-standard namespaces already in use in Electrum-NMC such as id/ which is owned by @domob1812 himself. 

Second, yanmaani is not a developer, he is just crying for money and when @JeremyRand is stupid enough to pay this clown, he will ask on IRC others to write some shit what he merge as his own. 

@yanmaani and rllola tried unsuccessfully to bully people in other repositories to merge they namecoin related code which was rejected immediately. So overall, just to note, @yanmaani is a clown, not a developer for this project. 

Honestly, @domob1812 is a cybersquatter too. He also has thousands of domains ready for sale. 

Those who say that "no squatting" problem in the d/ namespace is either full retarded or he himself is a squatter. The d/ namespace is completely squatted. 

Back in 2012 there was already a big problem with squatters in the d/ namespace, then @phelixbtc tried to auction the squatted names in https://bitcointalk.org/index.php?topic=66212 to wich the response [was](https://bitcointalk.org/index.php?topic=66212.msg768444#msg768444) the following: 

## God I fucking hate domain squatters.  The scummy underbelly of the major TLDs and now in Namecoin as well.
## You guys are suck fucksticks, I hope you die.  Well, if it's not you, it's some other cockgobbler doing it, so might was well make a buck, huh?

@phelixbtc give everything to @domob1812 who now trying to sell names from the d/ namespace for millions of dollars.

**Comment by blocktraveler** [comment]
>     * Zoltán Kondér is not `onehundrednmcpername@protonmail.com`.

I see, ZK has just warmed up. 🤣🤣🤣 But I'd really like to know how @yanmaani got that insider knowledge, as even the code contributors here don't know who's the 100NMC-man...

**Comment by domaindeals** [comment]
All of them are squatters apart from @JeremyRand, @domob1812 squatting around 20,000 names, @yanmaani himself makes money by squatting and reselling names for 150-200 dollars. 

Still.. you're the biggest sucker Uwe Martens @blocktraveler. You should be sued in Germany and imprisoned for IP fraud.

**Comment by domaindeals** [comment]
Uwe Martens a few hours ago squatted `d/zeronetwork`! `zeronetwork.bit`was the official .bit domain for ZeroNet.

cc: @JeremyRand @yanmaani

**Comment by blocktraveler** [comment]
My heart is bleeding! Now **Uwe Martens**, the mad fraudster and cyberquatter, will squat on it until he gets 10 ETH on his wallet! Legal actions have to be taken against him, everyone contact Telegram and the authorities to get him finally imprisoned! And **Zoltan Konder** is being finally awarded of being the Savior of the whole Namecoin project! 🤣🤣🤣🤣🤣🤣

Of course the domain had to be secured from the known hobby grabbers. According to our [Domain trading policy](https://namecoin.pro/SitePages/Namecoin%20in%20competition.aspx#Policy) it will be transferred or set up on behalf for free if Tamas Kocsis confirms his official usage. He got already contacted.

**Comment by domaindeals** [comment]
You not get anything for it but a handcuff. Tamas will punch you in the face if he finds you. Keep sending him messages. Funny how this scum trying to turn the topic against a Zoltan which also a Hungarian name like Tamas and appears that Zoltan is working on ZeroNet with Tamas. 

**Uwe Martens** trying to bully other people in his own topic. Which created specifically to expose hes fraudulent criminal threats against the Namecoin project, harassment of the NLnet Foundation, CoinMarketCap, Namecoin, and now even demanding 10 ETH from the ZeroNet project too. about squatting. 

> Of course the domain had to be secured from the known hobby grabbers. According to our [Domain trading policy it will be transferred or set up on behalf for free if Tamas Kocsis confirms his official usage. He got already contacted.

Someone opened a topic about you here, that you squatting in the d/ namespace and you while the topic is still open attacked another major project. 

> Uwe Martens, the mad fraudster and cybersquatter, will squat on it until he gets 10 ETH on his wallet! 

You yourself are a cybersquatter or grabber as you call yourself: 

![cybersquatter-grabber](https://user-images.githubusercontent.com/106484358/170973530-95539f40-a2ca-4818-b0de-9d49b6410362.png)

Regarding your namecoin.pro website, both @JeremyRand and everyone else including Zoltan (who compared to you has contributed to Namecoin) has stated that your website is not affiliated with Namecoin, you're not a contributor to Namecoin. You spamming your shit website here in this thread, on the talk page of the Namecoin WikiPedia article, on Reddit, on BitcoinTalk even on CoinMarketCap. 

You have been trying to bully everyone from NLnet Foundation to @JeremyRand even calling https://namecoin.org a scam by Jeremy Rand. 

Saying that you give the d/zeronetwork for Tamas Kocsis while you already spammed that domain with a "domaindeals.pro" link on the block chain will not work. **Every single domain that has domaindeals.pro value or had that value are completely worthless because everyone knows that Uwe Martens the cybersquatter criminal who pretends to be a Namecoin Developer and representative of the Namecoin project trying to get 10 ETH for them!** 

Uwe Martens currently trying to sell shit domains from 2014 for 0.1 ETH using the fake Namecoin Telegram channel https://t.me/telegram.

**Comment by domaindeals** [comment]
@yanmaani @JeremyRand @domob1812 @khalahan @phelixbtc We have to abandon the d/ namespace and move to another to bankrupt the squatters like Uwe Martens.

Saying that the move is disastrous if false. There is not a single .bit domain which is used today apart from namecoin.bit. Moving the namespace would open up Namecoin for newcomers and we can raise registration price in the new namespace to much higher so these squatters would not have a chance. 

Applications already using the d/ namespaces wouldn't be affected at all. I urging everyone to move the Namespace immediately.

**Comment by blocktraveler** [comment]
For the readers here: It should be noted that Zoltan Konder has already created several puppet accounts here and created with each puppet a GitHub "fork" of the Namecoin repo, just to give the impression of somehow being involved in the development of Namecoin. His biggest “achievement” was an amateurish modified logo SVG for the Electrum wallet (which has never been implemented of course). Sometimes he was hanging around in the IRC dev channels to learn from @yanmaani how to code with Python, especially after creating his own forked repo of Zeronet. In fact, he does not contribute to Zeronet in any way that he claims to. This user has been and will be banned globally in about 1k crypto-related groups on Telegram and in all Discord servers as soon as a sockpuppet is discovered. Nobody, absolutely nobody is collaborating with that toxic user. Last but not least, it has to be mentioned that the only reason for him to join the Namecoin project was the fact that his ICANN domain [abused for his scam foundation](https://archive.ph/mgmyu) got suspended. Unfortunately Namecoin has always attracted this kind of clientele, so just report, block and ignore. This Github repo was his last resort and the stage should finally be closed for good now.

**Comment by domob1812** [comment]
I don't think there's any useful content posted here, especially not related to Namecoin Core.
