### ISSUE TITLE
Duplicate name creation allowed

### ISSUE THREAD

**Issue by xloem** [namecoin/namecoin-core#54]
namecoin-cli will happily create a name_new for a name which already exists.  It should check for this and fail.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

I definitely agree that it shouldn't allow this by default.  There are
some rare circumstances where it is useful to issue a name_new for a
name that already exists.  In particular, if the name is expected to
expire within 12 blocks, then name_new can be safely issued.

Maybe disallow it by default, but add an optional parameter that
enables name_new in such cases if set to 1?
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWgXv9AAoJEAHN/EbZ1y06yRUP/0j7acF2ceBegF8D4ahw1zEA
8y/8SBsdjF2uQyjQ0/4uApukpkvP9ywnWPj7M+hSqOu5qQk5Krqd/C1nZrSstgnJ
NV86yaekSzKzQ5PCqkihc7wZ3e/uv4FDOTliYQyGHzdBhL2nodL/Pcx73TARVzhj
WTwmhOm5Wsv+S3SEq1o8/9E7vKMkPcSrs3XM2GmxdqzxnGFt6hXRiWC7CWya87Vt
pHI5NieIPrD4KdO8nP92F5BziNu4NwiFvbNk7pzksTyAHR5Q4wx6tEDptQPVR5yC
WPbjIEGUuvt7cmClcBdm50vmoYSUWZwe3D4h1tOwViPsuEGuv5URicR6EtC3H8aI
vneiyVVWManqJXtvaxATSY0nkmkj5A6CdejOzQh5DJ0oM7dgQeJ+2KKKbn4tp9Ip
1+gIBpAPysYLzw1/neuQkDgFCZbK2526CV1CS0UyobzGt01R1AQ4i7nInzT34ELT
86T6LbhJFNB0myug74ureHSn0dohihs4hczKrV299xS9TyjcgoYrl8JJYvjBojSX
EZU9yMRDjD+AWJ+o/KJ15M901eOW+VhRSlcehm0LWhwdk0uTODQgsgBk6JNJmglD
lr005Ym8YR5HOTMAgDfZUe0eHUtkws/9G759+6AGrZUDpo/qrUw+knC+wFzFiCjm
wg1TFmcEMUhmxEptxlcD
=6S3V
-----END PGP SIGNATURE-----

**Comment by domob1812** [comment]
I agree with @JeremyRand that this is at least a partially intended and useful "feature".  I think at least the experienced users are well aware of it.  But I also agree that an additional "safety switch" could be added.  Should we do that?  In order to make the most sense, the default behaviour must be changed from allow to disallow duplicate name reservation - this has the potential to confuse people who are relying on the old behaviour; but I guess this is mostly a theoretical concern and don't think this will be a real problem.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Generally, the people relying on the current behavior are name
speculators and other power users; I think it's likely that they will
be more than capable of fixing their code if we make the default to
disallow duplicate name reservations.

So yes, I think a safety switch should be added, with the default
behavior to disallow duplicate name reservations.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWg1s0AAoJEAHN/EbZ1y06pTcP/3RsxU/Ae4ituxynr+0sVCIX
IsJ2J4g/g/e0igGapaDreF5uMlMSYQoPqacww+rKUbLIsJYgXoDnkNxjycTmS5DX
XtHf5tcJ6aDRS7FFgi8JMB/E+zX3oiUIC7PKrD+54PIOfuIhG+kq3X7F2zRq+65e
wba7DcPlDbMu9saBPtysvcdjUgwP3Quh+8731eEk2FCj9R2csNUF+JmgydiykgnX
aw3n7mZG9sL67oZduvUHK+GLHhQgH/MO5HjXWnFqPjZJ+h1GGN9R5PD7W6CtV94A
7TrojRiAWdtrO90t+LdrhIUChdrX5va6Z/K/lFzKMA2cMPpfjxmbLz660iPPUkwh
PbDusbhATjPB+kiI/7xelS/llNGWONVBXaVYiSMKSYXCkF8PlNMA1kDEzU4IieHI
dzs66KZm3+49rUzkjdnBHjyZleAi/fuxYwMhyhbLPs6rTqLbCwWStgcZU67t9hY6
VFTwVlbPRTsKdxELsFJeMdmM9AjJAtP3XtfwL1SS210aJfBryXydab/3T91NlT+r
wnmckcH70vkEh6/VCosekFzRDmzRZ5/GmB7ac281GpM5jJrSRo2YpGenpuEh7mJB
OJo5FKWr/jVVlWib8ki6ZqTIvDJZXDasTr0S+71JOCuA/QmkqVIjpRp5s9lNQaCC
oE3Kg6EdVkG+AwJIu9B1
=59qS
-----END PGP SIGNATURE-----

**Comment by domob1812** [comment]
I agree, just wanted to point that out.  Let's wait a bit if anyone else has feedback, then I'll create a patch.

**Comment by domob1812** [comment]
Apparently no more feedback, so I think I'll work on a patch in the future.

**Comment by phelixbtc** [comment]
IMHO this is low priority and should be catched in a user interface. With the command line you need to know what you are doing.

**Comment by JeremyRand** [comment]
@phelixbtc A fix doesn't have a huge impact on most users, but it's also presumably relatively low-effort to fix, and the earlier it's fixed, the better, since it affects stability of our API.  Making things unnecessarily hard for users just because they choose to use the command line doesn't seem to be particularly user-friendly.

**Comment by phelixbtc** [comment]
@JeremyRand This is not really an issue. It is not even clear the suggested change would be an improvement as it complicates the codebase and usability for the 99% of users who never run into this problem ("I've lost my keys and now I wan't to catch my name back because name_new does not work what should I do?"). There really are way more important things.  

At the very least a "fix" should give directions on how to override the default.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

@phelixbtc What 99% of users are you talking about?  With the current
UX, if you want to register a new name from the CLI, you have to do
name_show to check that the name is available, followed by name_new.
With the proposed UX, you just do name_new.  That is much simpler; new
CLI users are unlikely to guess that they need to do name_show first.

Certainly the proposed error message should give explicit instructions
to bypass the warning.  But those instructions aren't particularly
complicated.  Would probably be as simple as adding an extra optional
boolean argument at the end of the CLI command if you want to bypass
the warning.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWn1PPAAoJEAHN/EbZ1y06SqoQAKvbm2fVjBONEt5Akq64u3MI
9Ev2vV5Cy3NAG1WtBhil1U4EBuzDlpZEjgj8VdcEXLn4KwesGwrR41TklsaZN95g
fuiw8e9jVGBx6dP7ajxC97eQWxpWz8Nc29EE0jk4/0TgcIj9W1vO2j0C/BSZLxGC
UPsWpS4JEsHuh9S9c14qbSwXxdu7S7gOf+DQm1DPPhvJip2b2O3bhOpM0xYb5UZ7
LKqlaY13EezW++K7qd+rBKZdkjyxxLzAzkoOV8eaXX4Wnico3CkCIp+WHiH9VF+g
apwm5HFmDPRrKfVm0P2nop4RdBeuP42ooO4rD88GS1aQtSgH4lY0erzv9cCP/suQ
dXQRC/rE3WBLgfxNmrPQs8kigDBV3SN4hpvwXy7ZxfWEgj8Dj8MOOFnzdfvrcs4t
5NRSHk1LS62x7iq7JqviJ9qZ2thiNv5KeRZZpim9iQcbjKUXXcufwsCkxclCBc4M
Kja914IZ5ib7VvamHGpuDUqFj95au4to18G4lwAve1sKa1Zv9gu9MltHC8npzgj/
atpIx80LEcyxX6tqS4g+Q+AmMbTStHCnZ3tTVpjuAknhK9XuMp1tukIzixOkUITT
i1L12yvAGevoZGQLk78IfmCQN9jv1HHrqo6nfbz0szuT36ITAYK6+htaZOqOdmkR
hVW5M8bwKZfUpwaaIWlI
=jBRj
-----END PGP SIGNATURE-----

**Comment by domob1812** [comment]
I think this is a useful feature, although not high in priority.  We should do this based on #194.
