### ISSUE TITLE
Rescue priority-related code from v0.11 to v0.12

### ISSUE THREAD

**Issue by wangchun** [namecoin/namecoin-core#64]
Bitcoin Core v0.12 set default priority size to zero and simplified many priority calc-related code. This does not apply to Namecoin. We need to bring these removed code back.

**Comment by domob1812** [comment]
Why do you think that this does not apply to Namecoin?  IMHO, there is no real difference with respect to these things in Namecoin.  (One could even argue that free, priority-related transactions are even less useful in Namecoin than they are in Bitcoin, since Namecoin is meant to be mostly about name transactions, and totally free name updates should not be allowed anyway.)

**Comment by phelixbtc** [comment]
This is an interesting topic. When I heard Bitcoin would remove priority transactions it was a bit of a shock first but when I looked into their arguments they were convincing.  
I also see some differences with Namecoin (less transactions and flooding is way cheaper) so if it was only about changing a parameter I would agree that we should keep the priority space. But de facto it would mean a lot of work. IMHO we should rather put that effort into application development to attract some actual users and increase the price - this would also make flooding more difficult.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

I admit that I'm not familiar with the upstream Bitcoin Core changes,
but I don't see a reason to encourage free name transactions.
Squatting is problematic enough that I honestly would prefer that most
miners voluntarily enforce transaction fees to drive up the cost of
mass-squatting.  I am skeptical that such self-regulation will be
effective, but at the very least, I don't see a reason for us to go to
extra effort in order to make it easier for miners to make it easier
for squatters.

@phelixbtc I think the fact that flooding is cheaper on Namecoin
actually is an argument for increasing fees, as it acts as a rate
limiter on flooding.

Am I missing something?  @wangchun , is there a reason that you think
we should spend effort making free transactions easier?

Cheers.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWudJaAAoJEAHN/EbZ1y06utsP/18CkS2fZScrv+E0JPMpkRMH
Gfq2BtYb0oBi7SE/mkzAmS5i3N89KJxE7G4LJBganVyqmnvg9jvEEUx1mgtmgjAQ
0TnQxny0f3mx6kBWn5QkXi3qWyphgDY56hAIn48szqCq6c2yVjQ6ac/oF/J/PzmZ
yMlc8qKx2SfIYjjAuilyTlnIWIy7ZGzpuYZpwkdzwAIEyOW5kcUYW6zZQBpWwpXo
lBF+HGax5/cfyOkag9v9f13yZrTTAKOzS+id+wBLHW07kbrDj1nvpVhoh9TkMrUb
cXJYe9UzDcE17AyU3R0Eoidaw10XWVlRskO/sBNpIn2xJTAC/QY9Lu3uFAXDluCu
CpES+Jo92ntsZO8hK3AMuz9KIPcn/zVrD6iQvS6uSXZBO0QTedaSXHUOw6K+BH8F
YsQq3E2HcxEOBwLlBk4caISDayYOKAwgkjf8/hC+owbxFz0xapfkoLqkrhpUndJE
acVT3DIodii0NwqePoXL7igMU/Ntcc/q7nCVX/hcnWG/K49zgjHdn71RoQvMnQ/2
KoQtFzf0hlYf12XbzvaDVuONMBRvXSsavRjPXIH9hM8bzVort/Sf9qkMeao/E75M
LgZXdCWiXTUJpCpRDoTPEnT1E2H3I/2EuUQYLT30oZAj19twxim2S7BUmnMwNoBR
pwy+1erYlsFYo+EOlUJr
=UX1R
-----END PGP SIGNATURE-----

**Comment by phelixbtc** [comment]
@JeremyRand this is not really about free transactions but about preventing somebody from stalling the network by flooding: https://bitcointalk.org/index.php?topic=148211.0  Nowadays transaction fee height is dynamic to some extend so it should be way more expensive to impact the network for a noticable time.

**Comment by wangchun** [comment]
@JeremyRand I don't know. I raised this issue because I think not every change made for Bitcoin should be blindly applied to altcoins. If most of you think free transactions are also bad for namecoin, I would have no problem.

**Comment by domob1812** [comment]
This code is long gone, so let's close this as obsolete.
