### ISSUE TITLE
Reset testnet or add checkpoints?

### ISSUE THREAD

**Issue by jonasbits** [namecoin/namecoin-core#74]
Right now our testnet is a mess. This is not a big problem because you can develop in regtest mode but new developers should be able to use testnet as a starting point.

I was using the bitcoin-seeder code to find testnet nodes, and there are to few. And even less that are running Namecoin Core. Old clients now accept and mine with version 1 blocks and new clients do not.

Is Namecoin Core Testnet2 the solution?

**Comment by domob1812** [comment]
I have no particularly strong opinion on that.  First of all, we should try to reach out to the unupdated nodes and see if we can get them fixed.  Adding a checkpoint is also fine, not sure about resetting the network.  Other opinions?

**Comment by JeremyRand** [comment]
Generally, Bitcoin's policy seems to be that any time the usefulness of testnet is disrupted, the testnet gets reset.   The two times this has happened for Bitcoin, were related to disruption caused by the exchange rate (some people were trying to sell testcoins), and disruption caused by misbehaving miners (some people dumped lots of hashrate onto the network, ramped up the difficulty, and then left the network, causing blocks to not get mined).  It is my opinion that what amounts to a large, highly disruptive chainfork definitely fits with these other two cases.  So I would support resetting the testnet.

Thoughts?

**Comment by domob1812** [comment]
I suggest making this non-blocking for the release so that we can go ahead with the BIP9-fork - but if someone wants to set up the new testnet, then I'm happy to review and merge pull requests.

**Comment by JeremyRand** [comment]
Agreed, I think this is sufficiently noncritical that we can push it back until after the BIP9 hardfork.

**Comment by domob1812** [comment]
Does anyone know what the current state of the testnet is?  I've not used it for quite some time.  Are the forks still an issue?  I can imagine that most nodes are updated by now and the ones which are not simply gone offline over time.

**Comment by dedotombo** [comment]
The testnet does not work for me, "no block sources".
